services:
  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./app/frontend:/app
      - ./app/backend:/backend
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - EXPO_PUBLIC_API_URL=http://localhost:3002
    depends_on:
      - backend

  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./app/backend:/app
      - sqlite-data:/data
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PORT=3002
      - NODE_ENV=${NODE_ENV:-development}
      - JWT_SECRET=${JWT_SECRET}
      - S3_ENDPOINT=http://minio:9000
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-minioadmin}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-minioadmin}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STRIPE_MONTHLY_PRICE_ID=${STRIPE_MONTHLY_PRICE_ID}
      - FRONTEND_URL=http://localhost:8081

  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: "listen --api-key ${STRIPE_SECRET_KEY} --forward-to backend:3002/billing/webhook"
    environment:
      - STRIPE_API_KEY=${STRIPE_SECRET_KEY}
    depends_on:
      - backend

volumes:
  minio-data:
  sqlite-data: 