services:
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - DATABASE_URL=file:/app/prisma/dev.db
      - JWT_SECRET=development-secret-key
      - NODE_ENV=development
      - S3_ENDPOINT=http://minio:9000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_REGION=us-east-1
    volumes:
      - ./app/backend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - minio

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    ports:
      - "19100:19000"
      - "19101:19001"
      - "19102:19002"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=localhost
      - EXPO_PUBLIC_API_URL=http://backend:3002
    volumes:
      - ./app/frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

volumes:
  minio-data: 