version: '3.8'

services:
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile.prod
      args:
        - NODE_ENV=production
    ports:
      - "3002:3002"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PORT=3002
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=production
      - S3_ENDPOINT=${S3_ENDPOINT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    restart: unless-stopped
    depends_on:
      - minio

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile.prod
      args:
        - NODE_ENV=production
    ports:
      - "8081:8081"
      - "19000:19000"
    environment:
      - EXPO_PUBLIC_API_URL=${EXPO_PUBLIC_API_URL}
      - PORT=8081
    restart: unless-stopped
    depends_on:
      - backend

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    restart: unless-stopped

volumes:
  minio-data: 