services:
  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./app/frontend:/app
      - ./app/backend-js-api:/backend-js-api
      - /app/node_modules
      - /backend-js-api/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./app/backend:/app
      - /app/node_modules
      - sqlite-data:/data
    environment:
      - PORT=3002
      - NODE_ENV=development
    depends_on:
      - minio

  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    restart: unless-stopped

volumes:
  minio-data:
  sqlite-data: 