// This file is auto-generated by @hey-api/openapi-ts

export type GetPingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ping/';
};

export type GetPingResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetPingAuthData = {
    body?: never;
    headers?: {
        authorization?: string;
    };
    path?: never;
    query?: never;
    url: '/ping/auth';
};

export type GetPingAuthErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetPingAuthResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetPingAdminData = {
    body?: never;
    headers?: {
        authorization?: string;
    };
    path?: never;
    query?: never;
    url: '/ping/admin';
};

export type GetPingAdminErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetPingAdminResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostAuthLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginResponses = {
    default: unknown;
};

export type PostAuthRegisterData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type PostAuthRegisterErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Conflict
     */
    409: unknown;
};

export type PostAuthRegisterResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type GetFoldersByFolderIdContentsData = {
    body?: never;
    headers?: {
        authorization?: string;
    };
    path: {
        folderId: string;
    };
    query?: never;
    url: '/folders/{folderId}/contents';
};

export type GetFoldersByFolderIdContentsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetFoldersOrgByOrganizationIdData = {
    body?: never;
    headers?: {
        authorization?: string;
    };
    path: {
        organizationId: string;
    };
    query?: never;
    url: '/folders/org/{organizationId}';
};

export type GetFoldersOrgByOrganizationIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetFoldersProjectsOrgByOrganizationIdData = {
    body?: never;
    headers?: {
        authorization?: string;
    };
    path: {
        organizationId: string;
    };
    query?: never;
    url: '/folders/projects/org/{organizationId}';
};

export type GetFoldersProjectsOrgByOrganizationIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetFoldersByFolderIdHierarchyData = {
    body?: never;
    headers?: {
        authorization?: string;
    };
    path: {
        folderId: string;
    };
    query?: never;
    url: '/folders/{folderId}/hierarchy';
};

export type GetFoldersByFolderIdHierarchyErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type PostFoldersData = {
    body?: never;
    headers?: {
        authorization?: string;
    };
    path?: never;
    query?: never;
    url: '/folders/';
};

export type PostFoldersErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type DeleteFoldersByFolderIdData = {
    body?: never;
    headers?: {
        authorization?: string;
    };
    path: {
        folderId: string;
    };
    query?: never;
    url: '/folders/{folderId}';
};

export type DeleteFoldersByFolderIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type PostProjectsData = {
    body?: never;
    headers?: {
        authorization?: string;
    };
    path?: never;
    query?: never;
    url: '/projects/';
};

export type PostProjectsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type DeleteProjectsByProjectIdData = {
    body?: never;
    headers?: {
        authorization?: string;
    };
    path: {
        projectId: string;
    };
    query?: never;
    url: '/projects/{projectId}';
};

export type DeleteProjectsByProjectIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetProjectsByProjectIdData = {
    body?: never;
    headers?: {
        authorization?: string;
    };
    path: {
        projectId: string;
    };
    query?: never;
    url: '/projects/{projectId}';
};

export type GetProjectsByProjectIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type PutProjectsByProjectIdData = {
    body?: never;
    headers?: {
        authorization?: string;
    };
    path: {
        projectId: string;
    };
    query?: never;
    url: '/projects/{projectId}';
};

export type PutProjectsByProjectIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetProjectsOrgByOrganizationIdData = {
    body?: never;
    headers?: {
        authorization?: string;
    };
    path: {
        organizationId: string;
    };
    query?: never;
    url: '/projects/org/{organizationId}';
};

export type GetProjectsOrgByOrganizationIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetAdminUsersData = {
    body?: never;
    headers?: {
        authorization?: string;
    };
    path?: never;
    query?: never;
    url: '/admin/users/';
};

export type GetAdminUsersErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type PutAdminUsersByUserIdRoleData = {
    body?: never;
    headers?: {
        authorization?: string;
    };
    path: {
        userId: string;
    };
    query?: never;
    url: '/admin/users/{userId}/role';
};

export type PutAdminUsersByUserIdRoleErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type PutAdminUsersByUserIdRoleResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteAdminUsersByUserIdData = {
    body?: never;
    headers?: {
        authorization?: string;
    };
    path: {
        userId: string;
    };
    query?: never;
    url: '/admin/users/{userId}';
};

export type DeleteAdminUsersByUserIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};