name: Backend Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'app/backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'app/backend/**'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack
        env:
          SERVICES: s3
          DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
        ports:
          - 4566:4566

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: app/backend/package-lock.json

    - name: Install dependencies
      working-directory: app/backend
      run: npm ci

    - name: Generate Prisma Client
      working-directory: app/backend
      run: npx prisma generate

    - name: Run tests
      working-directory: app/backend
      env:
        DATABASE_URL: "file:./prisma/test.db"
        JWT_SECRET: "test-secret-key"
        NODE_ENV: "test"
        S3_ENDPOINT: "http://localhost:4566"
        AWS_ACCESS_KEY_ID: "test"
        AWS_SECRET_ACCESS_KEY: "test"
        AWS_REGION: "us-east-1"
        S3_BUCKET: "voicecad-files"
      run: |
        npm test

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }} 